apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: python-joinville-deployment
  labels:
    app: python-joinville
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-joinville
  template:
    metadata:
      labels:
        app: python-joinville
    spec:
      containers:
      - name: python-joinville
        image: cleberwarmling/python-joinville:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
